name: Node.js CI and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    ##- run: npm test

    - name: Compress Files
      run: cd dist/tarea7_cloud2024 && zip -r build.zip . && cd ../..

    - name: Create and Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create tarea7.${{ github.sha }} \
          --title "Tarea 7 Cloud ${{ github.sha }}" \
          --notes "Release notes for Tarea 7 Cloud" \
          --draft \
          ./dist/tarea7_cloud2024/build.zip#build-${{ github.sha }}.zip

    - name: Publish Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release edit tarea7.${{ github.sha }} --draft=false
